async function main() {
  try {
    console.log('Main completed');
  } catch (err) {
    console.log('Error: ', err);
  }
}

main();
